"""Report generator for enhanced weekly summaries.

Takes WeeklyMetrics and produces a rich Slack Block Kit message with:
- Executive summary (key numbers + deltas)
- ASCII burndown chart
- Team breakdown
- Oldest risks
- New risks this week
- Shout-outs

Usage:
    generator = ReportGenerator()
    message = generator.build_weekly_report(metrics)
    slack.send_to_channel(channel, message)
"""

import logging
from datetime import date
from typing import Dict, List

from .metrics_calculator import WeeklyMetrics

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates rich Slack Block Kit reports from computed metrics.

    Usage:
        gen = ReportGenerator()
        msg = gen.build_weekly_report(metrics)
    """

    def build_weekly_report(self, metrics: WeeklyMetrics) -> Dict:
        """Build the full weekly report as a Slack message.

        Args:
            metrics: Computed WeeklyMetrics from MetricsCalculator.

        Returns:
            Slack message dict with 'text' and 'blocks'.
        """
        title = f"MCE Risk Register Weekly Summary - {date.today().strftime('%B %d, %Y')}"
        blocks = []

        # Header
        blocks.append({
            "type": "header",
            "text": {"type": "plain_text", "text": f"\U0001f4ca {title}"},
        })

        # Executive summary
        blocks.append(self._build_executive_summary(metrics))
        blocks.append({"type": "divider"})

        # Burndown
        burndown_block = self._build_burndown(metrics)
        if burndown_block:
            blocks.append(burndown_block)
            blocks.append({"type": "divider"})

        # Team breakdown
        blocks.append(self._build_team_breakdown(metrics))
        blocks.append({"type": "divider"})

        # Oldest risks
        blocks.append(self._build_oldest_risks(metrics))

        # New risks this week
        if metrics.new_risks:
            blocks.append({"type": "divider"})
            blocks.append(self._build_new_risks(metrics))

        # Shout-outs
        if metrics.shout_outs:
            blocks.append({"type": "divider"})
            blocks.append(self._build_shout_outs(metrics))

        # Footer
        blocks.append({"type": "divider"})
        blocks.append({
            "type": "context",
            "elements": [{
                "type": "mrkdwn",
                "text": (
                    "\U0001f4cb <https://gus.lightning.force.com/lightning/r/Dashboard/"
                    "01ZEE000001Bgkv2AC/view|View Full Dashboard> • "
                    "Generated by Risk Register Automation"
                ),
            }],
        })

        return {"text": title, "blocks": blocks}

    def _build_executive_summary(self, metrics: WeeklyMetrics) -> Dict:
        """Build the key metrics section with deltas."""
        # Format deltas
        open_delta_str = ""
        if metrics.open_delta is not None:
            arrow = "↓" if metrics.open_delta < 0 else "↑" if metrics.open_delta > 0 else "→"
            open_delta_str = f" ({arrow} {abs(metrics.open_delta)} from last week)"

        compliance_pct = f"{metrics.compliance_rate * 100:.0f}%"
        compliance_delta_str = ""
        if metrics.compliance_delta is not None:
            arrow = "↑" if metrics.compliance_delta > 0 else "↓" if metrics.compliance_delta < 0 else "→"
            compliance_delta_str = f" ({arrow} {abs(metrics.compliance_delta * 100):.0f}%)"

        velocity_str = f"{metrics.avg_closed_per_week:.1f}/week" if metrics.avg_closed_per_week > 0 else "N/A"

        text = (
            f"*\U0001f4c8 Key Metrics*\n"
            f"• Total Open Risks: *{metrics.total_open}*{open_delta_str}\n"
            f"• Stale (Need Review): *{metrics.total_stale}*\n"
            f"• Review Compliance: *{compliance_pct}*{compliance_delta_str}\n"
            f"• Closed This Week: *{metrics.newly_closed}*\n"
            f"• New This Week: *{metrics.newly_added}*\n"
            f"• Avg Closure Velocity: *{velocity_str}*"
        )

        return {"type": "section", "text": {"type": "mrkdwn", "text": text}}

    def _build_burndown(self, metrics: WeeklyMetrics) -> Dict:
        """Build an ASCII burndown chart from historical data."""
        if len(metrics.burndown) < 2:
            return None

        lines = ["*\U0001f4c9 Risk Burndown (Last 4 Weeks)*"]

        for i, point in enumerate(metrics.burndown):
            week_label = f"Week {i + 1}" if i < len(metrics.burndown) - 1 else "Now"
            delta_str = ""
            if point.delta is not None:
                if point.delta < 0:
                    delta_str = f" (↓ {abs(point.delta)})"
                elif point.delta > 0:
                    delta_str = f" (↑ {point.delta})"

            # Simple bar chart
            bar_len = min(point.total_open, 30)
            bar = "█" * bar_len
            lines.append(f"`{week_label:>6}:` {bar} *{point.total_open}*{delta_str}")

        text = "\n".join(lines)
        return {"type": "section", "text": {"type": "mrkdwn", "text": text}}

    def _build_team_breakdown(self, metrics: WeeklyMetrics) -> Dict:
        """Build the team breakdown section."""
        lines = ["*\U0001f465 By Team (Top 10):*"]

        for tm in metrics.team_metrics[:10]:
            closed_str = ""
            if tm.closed_this_week > 0:
                closed_str = f" ⭐ closed {tm.closed_this_week}"

            lines.append(
                f"• {tm.team_name}: *{tm.stale_count}* stale "
                f"({tm.high_impact_count} high impact){closed_str}"
            )

        return {"type": "section", "text": {"type": "mrkdwn", "text": "\n".join(lines)}}

    def _build_oldest_risks(self, metrics: WeeklyMetrics) -> Dict:
        """Build the oldest stale risks list."""
        lines = ["*⏰ Oldest Stale Risks:*"]

        for i, risk in enumerate(metrics.oldest_stale[:5], 1):
            name = risk["name"][:50]
            days = risk["days"]
            owner = risk["owner"]
            url = risk.get("gus_url", "")
            if url:
                lines.append(f"{i}. <{url}|{name}> — *{days} days* ({owner})")
            else:
                lines.append(f"{i}. {name} — *{days} days* ({owner})")

        return {"type": "section", "text": {"type": "mrkdwn", "text": "\n".join(lines)}}

    def _build_new_risks(self, metrics: WeeklyMetrics) -> Dict:
        """Build the new risks this week section."""
        lines = ["*\U0001f195 New Risks This Week:*"]

        for risk in metrics.new_risks[:5]:
            impact_emoji = {"High": "\U0001f534", "Medium": "\U0001f7e1", "Low": "\U0001f7e2"}.get(risk.get("impact"), "⚪")
            lines.append(f"• {impact_emoji} {risk['name']} ({risk.get('team', 'Unknown')})")

        if len(metrics.new_risks) > 5:
            lines.append(f"_...and {len(metrics.new_risks) - 5} more_")

        return {"type": "section", "text": {"type": "mrkdwn", "text": "\n".join(lines)}}

    def _build_shout_outs(self, metrics: WeeklyMetrics) -> Dict:
        """Build the shout-outs section for teams doing well."""
        lines = ["*\U0001f389 Shout-Outs:*"]
        for shout_out in metrics.shout_outs[:3]:
            lines.append(f"• {shout_out}")

        return {"type": "section", "text": {"type": "mrkdwn", "text": "\n".join(lines)}}
